README.rst

Signed-off-by:James L Parry <jim_parry@bcit.ca>

Readme update - Turkish translation.completed

---

README.rst

Signed-off-by:James L Parry <jim_parry@bcit.ca>

Readme update - Indonesian translation.completed

---

language/bulgarian/form_validation_lang.php

See https://github.com/bcit-ci/CodeIgniter/commit/f42e78cfef6bc9de7ee1c04673d993d605f5b589

A Bulgarian translation of 'form_validation_error_message_not_set'. #78

---

language/swedish/form_validation_lang.php

Signed-off-by: Peter Denk <peter@skypay.se>

Added form_validation_error_message_not_set in Swedish.

---

language/spanish/calendar_lang.php
language/spanish/date_lang.php
language/spanish/db_lang.php
language/spanish/email_lang.php
language/spanish/form_validation_lang.php
language/spanish/ftp_lang.php
language/spanish/imglib_lang.php
language/spanish/migration_lang.php
language/spanish/number_lang.php
language/spanish/pagination_lang.php
language/spanish/profiler_lang.php
language/spanish/unit_test_lang.php
language/spanish/upload_lang.php

Spanish line added for #78. Also changed comments for https://github.com/bcit-ci/CodeIgniter/commit/fe9309d22c1b088f5363954d6dac013c8c955894.

Updated spanish translation

---

language/korean/calendar_lang.php
language/korean/date_lang.php
language/korean/db_lang.php
language/korean/email_lang.php
language/korean/form_validation_lang.php
language/korean/ftp_lang.php
language/korean/imglib_lang.php
language/korean/migration_lang.php
language/korean/number_lang.php
language/korean/pagination_lang.php
language/korean/profiler_lang.php
language/korean/unit_test_lang.php
language/korean/upload_lang.php

Korean translation

---

language/portuguese/calendar_lang.php
language/portuguese/date_lang.php
language/portuguese/db_lang.php
language/portuguese/email_lang.php
language/portuguese/form_validation_lang.php
language/portuguese/ftp_lang.php
language/portuguese/imglib_lang.php
language/portuguese/migration_lang.php
language/portuguese/number_lang.php
language/portuguese/pagination_lang.php
language/portuguese/profiler_lang.php
language/portuguese/unit_test_lang.php
language/portuguese/upload_lang.php

fixed the spacing;
removed php version from licence notices;
bump year number in copyright notice
added new translation line 'form_validation_error_message_not_set'

Happy new year :)

---

language/persian/calendar_lang.php
language/persian/date_lang.php
language/persian/db_lang.php
language/persian/email_lang.php
language/persian/form_validation_lang.php
language/persian/ftp_lang.php
language/persian/imglib_lang.php
language/persian/migration_lang.php
language/persian/number_lang.php
language/persian/pagination_lang.php
language/persian/profiler_lang.php
language/persian/unit_test_lang.php
language/persian/upload_lang.php

Update 2014 to 2014 - 2015
Change PHP request

Updating the copyright year for language persian

---

language/swedish/calendar_lang.php
language/swedish/date_lang.php
language/swedish/db_lang.php
language/swedish/email_lang.php
language/swedish/form_validation_lang.php
language/swedish/ftp_lang.php
language/swedish/imglib_lang.php
language/swedish/migration_lang.php
language/swedish/number_lang.php
language/swedish/pagination_lang.php
language/swedish/profiler_lang.php
language/swedish/unit_test_lang.php
language/swedish/upload_lang.php

Updated Swedish copyright messages

---

language/polish/calendar_lang.php
language/polish/date_lang.php
language/polish/db_lang.php
language/polish/email_lang.php
language/polish/form_validation_lang.php
language/polish/ftp_lang.php
language/polish/imglib_lang.php
language/polish/migration_lang.php
language/polish/number_lang.php
language/polish/pagination_lang.php
language/polish/profiler_lang.php
language/polish/unit_test_lang.php
language/polish/upload_lang.php

Updating the copyright year for language polish

---

language/thai/calendar_lang.php
language/thai/date_lang.php
language/thai/db_lang.php
language/thai/email_lang.php
language/thai/form_validation_lang.php
language/thai/ftp_lang.php
language/thai/imglib_lang.php
language/thai/migration_lang.php
language/thai/number_lang.php
language/thai/pagination_lang.php
language/thai/profiler_lang.php
language/thai/unit_test_lang.php
language/thai/upload_lang.php

Updated Thai copyright messages

---

language/czech/calendar_lang.php
language/czech/date_lang.php
language/czech/db_lang.php
language/czech/email_lang.php
language/czech/form_validation_lang.php
language/czech/ftp_lang.php
language/czech/imglib_lang.php
language/czech/migration_lang.php
language/czech/number_lang.php
language/czech/pagination_lang.php
language/czech/profiler_lang.php
language/czech/unit_test_lang.php
language/czech/upload_lang.php

Update Czech header

---

language/traditional-chinese/calendar_lang.php
language/traditional-chinese/date_lang.php
language/traditional-chinese/db_lang.php
language/traditional-chinese/email_lang.php
language/traditional-chinese/form_validation_lang.php
language/traditional-chinese/ftp_lang.php
language/traditional-chinese/imglib_lang.php
language/traditional-chinese/migration_lang.php
language/traditional-chinese/number_lang.php
language/traditional-chinese/pagination_lang.php
language/traditional-chinese/profiler_lang.php
language/traditional-chinese/unit_test_lang.php
language/traditional-chinese/upload_lang.php

Updated traditional-chinese copyright messages

---

language/turkish/calendar_lang.php
language/turkish/date_lang.php
language/turkish/db_lang.php
language/turkish/email_lang.php
language/turkish/form_validation_lang.php
language/turkish/ftp_lang.php
language/turkish/imglib_lang.php
language/turkish/migration_lang.php
language/turkish/number_lang.php
language/turkish/pagination_lang.php
language/turkish/profiler_lang.php
language/turkish/unit_test_lang.php
language/turkish/upload_lang.php

Updated turkish copyright messages

---

language/dutch/calendar_lang.php
language/dutch/date_lang.php
language/dutch/db_lang.php
language/dutch/email_lang.php
language/dutch/form_validation_lang.php
language/dutch/ftp_lang.php
language/dutch/imglib_lang.php
language/dutch/migration_lang.php
language/dutch/number_lang.php
language/dutch/pagination_lang.php
language/dutch/profiler_lang.php
language/dutch/unit_test_lang.php
language/dutch/upload_lang.php

Update Dutch header comment

---

language/portuguese-brazilian/calendar_lang.php
language/portuguese-brazilian/date_lang.php
language/portuguese-brazilian/db_lang.php
language/portuguese-brazilian/email_lang.php
language/portuguese-brazilian/form_validation_lang.php
language/portuguese-brazilian/ftp_lang.php
language/portuguese-brazilian/imglib_lang.php
language/portuguese-brazilian/migration_lang.php
language/portuguese-brazilian/number_lang.php
language/portuguese-brazilian/pagination_lang.php
language/portuguese-brazilian/profiler_lang.php
language/portuguese-brazilian/unit_test_lang.php
language/portuguese-brazilian/upload_lang.php

Update copyright year and other comment info

Updating the header copyright comment for language portuguese-brazilian

---

language/romanian/calendar_lang.php
language/romanian/date_lang.php
language/romanian/db_lang.php
language/romanian/email_lang.php
language/romanian/form_validation_lang.php
language/romanian/ftp_lang.php
language/romanian/imglib_lang.php
language/romanian/migration_lang.php
language/romanian/number_lang.php
language/romanian/pagination_lang.php
language/romanian/profiler_lang.php
language/romanian/unit_test_lang.php
language/romanian/upload_lang.php

Updated Romanian copyright messages

---

language/french/calendar_lang.php
language/french/date_lang.php
language/french/db_lang.php
language/french/email_lang.php
language/french/form_validation_lang.php
language/french/ftp_lang.php
language/french/imglib_lang.php
language/french/migration_lang.php
language/french/number_lang.php
language/french/pagination_lang.php
language/french/profiler_lang.php
language/french/unit_test_lang.php
language/french/upload_lang.php

Update French header comment

---

language/simplified-chinese/calendar_lang.php
language/simplified-chinese/date_lang.php
language/simplified-chinese/db_lang.php
language/simplified-chinese/email_lang.php
language/simplified-chinese/form_validation_lang.php
language/simplified-chinese/ftp_lang.php
language/simplified-chinese/imglib_lang.php
language/simplified-chinese/migration_lang.php
language/simplified-chinese/number_lang.php
language/simplified-chinese/pagination_lang.php
language/simplified-chinese/profiler_lang.php
language/simplified-chinese/unit_test_lang.php
language/simplified-chinese/upload_lang.php

Updated simplified-chinese copyright messages

---

language/polish/form_validation_lang.php

Proposed Polish translation to address #78.

---

language/turkish/calendar_lang.php
language/turkish/form_validation_lang.php

form_validation_lang file: error_message_not_set message added,
calendar_lang file: Pz to Pa and Cts to Cmt because of more common usage

form_validation_lang and calendar_lang files changed

---

language/russian/form_validation_lang.php

Used Google translate.
@vadimyer, is this OK? 

Proposed Russian translation to address #78.

---

language/traditional-chinese/form_validation_lang.php

#78 
Human Translated
@PeterDaveHello Do you concur?

Proposed Traditional Chinese translation to address #78

---

language/norwegian/form_validation_lang.php

Proposed Norwegian translation to address #78.

---

language/persian/form_validation_lang.php

Proposed Persian translation to address #78.

---

language/romanian/form_validation_lang.php

Proposed Romanian translation to address #78.

---

language/arabic/form_validation_lang.php

@daif is this OK?
Signed-off-by:Heesung Ahn ahn.heesung@gmail.com

A Arabic translation of 'form_validation_error_message_not_set'. #78

---

language/czech/form_validation_lang.php

Used Google Translate.
@Ruplahlava is this OK?
Signed-off-by:Heesung Ahn <ahn.heesung@gmail.com>

A Czech translation of 'form_validation_error_message_not_set'. #78

---

language/portuguese-brazilian/form_validation_lang.php

Copied the translation from the Portuguese form_validation_lang.php
@mateusfbi, is this OK?
Please note: I closed the previous pull request that had a translation from Google Translate

Proposed Portuguese-Brazilian translation to address #78.

---

language/french/form_validation_lang.php

@includebeer do you concur?
Signed-off-by:Maxence Coulibaly <madmax330@yahoo.com>

French form validation updated #78

---

language/german/form_validation_lang.php

@Rufnex do you concurr?
Signed-off-by:Maxence Coulibaly <madmax330@yahoo.com>

German form validation updated #78

---

language/simplified-chinese/form_validation_lang.php

#78 
Human Translated
@denghongcai Do you concur?

Proposed Simplified Chinese translation to address #78

---

language/dutch/form_validation_lang.php

Used Google translate.
@pkrul is this OK?
Signed-off-by:Heesung Ahn <ahn.heesung@gmail.com>

A Dutch translation of 'form_validation_error_message_not_set'. #78

---

language/dutch/form_validation_lang.php

Hi Jim, 
Here the pull request to replace the Google-generated version from issue #78
Thanks!
Pieter

Correction for error_message_not_set in Dutch

---

language/spanish/calendar_lang.php
language/spanish/date_lang.php
language/spanish/db_lang.php
language/spanish/email_lang.php
language/spanish/form_validation_lang.php
language/spanish/ftp_lang.php
language/spanish/imglib_lang.php
language/spanish/migration_lang.php
language/spanish/number_lang.php
language/spanish/pagination_lang.php
language/spanish/profiler_lang.php
language/spanish/unit_test_lang.php
language/spanish/upload_lang.php

Removed EOF comments and added new lines at the end of the files.

Spanish update for #144

---

language/indonesian/calendar_lang.php
language/indonesian/date_lang.php
language/indonesian/db_lang.php
language/indonesian/email_lang.php
language/indonesian/form_validation_lang.php
language/indonesian/ftp_lang.php
language/indonesian/imglib_lang.php
language/indonesian/migration_lang.php
language/indonesian/number_lang.php
language/indonesian/pagination_lang.php
language/indonesian/profiler_lang.php
language/indonesian/unit_test_lang.php
language/indonesian/upload_lang.php

Indonesian Update for #144

---

language/spanish/calendar_lang.php
language/spanish/date_lang.php
language/spanish/db_lang.php
language/spanish/email_lang.php
language/spanish/form_validation_lang.php
language/spanish/ftp_lang.php
language/spanish/imglib_lang.php
language/spanish/migration_lang.php
language/spanish/number_lang.php
language/spanish/pagination_lang.php
language/spanish/profiler_lang.php
language/spanish/unit_test_lang.php
language/spanish/upload_lang.php

Updates Spanish to address #146.

New comment blocks for Spanish

---

language/italian/calendar_lang.php
language/italian/date_lang.php
language/italian/db_lang.php
language/italian/email_lang.php
language/italian/form_validation_lang.php
language/italian/ftp_lang.php
language/italian/imglib_lang.php
language/italian/migration_lang.php
language/italian/number_lang.php
language/italian/pagination_lang.php
language/italian/profiler_lang.php
language/italian/unit_test_lang.php
language/italian/upload_lang.php

Updates Italian to address #146.

New comment blocks for Italian

---

language/italian/form_validation_lang.php

Add italian form_validation_in_list message

---

language/spanish/form_validation_lang.php

Added spanish translation for the new form validation message.

Translated Spanish for #162

---

language/korean/form_validation_lang.php

Update New setting in form_validation_lang #162

---

README.rst

Readme update for pending 3.0 release

---

language/arabic/index.html
language/bulgarian/index.html
language/czech/index.html
language/dutch/index.html
language/french/index.html
language/german/index.html
language/index.html
language/indonesian/index.html
language/italian/index.html
language/japanese/index.html
language/korean/index.html
language/norwegian/index.html
language/persian/index.html
language/polish/index.html
language/portuguese-brazilian/index.html
language/portuguese/index.html
language/romanian/index.html
language/russian/index.html
language/simplified-chinese/index.html
language/spanish/index.html
language/swedish/index.html
language/thai/index.html
language/traditional-chinese/index.html
language/turkish/index.html
language/ukrainian/index.html

See https://github.com/bcit-ci/CodeIgniter/commit/b68a811f1a09b8d6012b6782b36a988daf68a82e

Unification of index.html files with those in CodeIgniter 3.

---

README.rst

Added Catalan translation

---

README.rst

Updated the readme to reflect the CI version that each translation is uptodate with.

Housekeeping.

---

language/traditional-chinese/form_validation_lang.php

Related issue #195
cc @PeterDaveHello

fix form_validation_in_list translation

---

language/hungarian/calendar_lang.php
language/hungarian/date_lang.php
language/hungarian/db_lang.php
language/hungarian/email_lang.php
language/hungarian/form_validation_lang.php
language/hungarian/ftp_lang.php
language/hungarian/imglib_lang.php
language/hungarian/index.html
language/hungarian/migration_lang.php
language/hungarian/number_lang.php
language/hungarian/pagination_lang.php
language/hungarian/profiler_lang.php
language/hungarian/unit_test_lang.php
language/hungarian/upload_lang.php

Signed-off-by: Lászlo Bóra <boralaszlo@gmail.com>

Added hungarian translation files

---

README.rst
language/khmer/calendar_lang.php
language/khmer/date_lang.php
language/khmer/db_lang.php
language/khmer/email_lang.php
language/khmer/form_validation_lang.php
language/khmer/ftp_lang.php
language/khmer/imglib_lang.php
language/khmer/index.html
language/khmer/migration_lang.php
language/khmer/number_lang.php
language/khmer/pagination_lang.php
language/khmer/profiler_lang.php
language/khmer/unit_test_lang.php
language/khmer/upload_lang.php

Dear Jim Parry,
I just translate CodeIgniter language to my language (Khmer), could you please accept my pull request!
Best Regards,
Chanthoeun Kim

Translate to Khmer language

---

README.rst
language/german/form_validation_lang.php
language/japanese/form_validation_lang.php
language/thai/form_validation_lang.php
language/turkish/form_validation_lang.php

Used google translate to provide missing translations for form_validation

Fix remaining language bundles; closes #195

---

language/turkish/form_validation_lang.php

form_validation_in_list translation

form_validation_in_list translation

---

language/tamil/calendar_lang.php
language/tamil/date_lang.php
language/tamil/db_lang.php
language/tamil/email_lang.php
language/tamil/form_validation_lang.php
language/tamil/ftp_lang.php
language/tamil/imglib_lang.php
language/tamil/index.html
language/tamil/migration_lang.php
language/tamil/number_lang.php
language/tamil/pagination_lang.php
language/tamil/profiler_lang.php
language/tamil/unit_test_lang.php
language/tamil/upload_lang.php

Tamil Translation for system messages created.

Tamil Translation for system messages

---

language/gujarati/calendar_lang.php
language/gujarati/imglib_lang.php
language/gujarati/migration_lang.php

Fixed extra comment closings in gujarati translations.

---

README.rst

Translations from @daif, but needed manual merge

Update arabic translations, fixes #194

---

language/russian/number_lang.php

Abbreviations changed in accordance with national standard GOST 8.417-2002 (ГОСТ 8.417-2002)

Abbreviations changed in accordance with national standard

---

language/russian/number_lang.php

Reverts bcit-ci/codeigniter3-translations#245

Revert "Abbreviations changed in accordance with national standard"

---

README.rst
language/vietnamese/calendar_lang.php
language/vietnamese/date_lang.php
language/vietnamese/db_lang.php
language/vietnamese/email_lang.php
language/vietnamese/form_validation_lang.php
language/vietnamese/ftp_lang.php
language/vietnamese/imglib_lang.php
language/vietnamese/index.html
language/vietnamese/migration_lang.php
language/vietnamese/number_lang.php
language/vietnamese/pagination_lang.php
language/vietnamese/profiler_lang.php
language/vietnamese/unit_test_lang.php
language/vietnamese/upload_lang.php

Added Vietnamese translation from Trần Xuân Sâm

---

README.rst
language/azerbaijan/calendar_lang.php
language/azerbaijan/date_lang.php
language/azerbaijan/db_lang.php
language/azerbaijan/email_lang.php
language/azerbaijan/form_validation_lang.php
language/azerbaijan/ftp_lang.php
language/azerbaijan/imglib_lang.php
language/azerbaijan/index.html
language/azerbaijan/migration_lang.php
language/azerbaijan/number_lang.php
language/azerbaijan/pagination_lang.php
language/azerbaijan/profiler_lang.php
language/azerbaijan/unit_test_lang.php
language/azerbaijan/upload_lang.php

Add Azerbaijan. Drop the suggested but not forthcoming translations.

---

language/japanese/form_validation_lang.php

Hi. I fixed form_validation_in_list written by google translated.

Fix form_validation_in_list

---

README.rst
language/slovak/calendar_lang.php
language/slovak/date_lang.php
language/slovak/db_lang.php
language/slovak/email_lang.php
language/slovak/form_validation_lang.php
language/slovak/ftp_lang.php
language/slovak/imglib_lang.php
language/slovak/index.html
language/slovak/migration_lang.php
language/slovak/number_lang.php
language/slovak/pagination_lang.php
language/slovak/profiler_lang.php
language/slovak/unit_test_lang.php
language/slovak/upload_lang.php

Added slovak language

---

language/japanese/number_lang.php

change バイト to B because gigabyte is GB, megabyte is MB, and so on.

change バイト to B

---

language/arabic/ftp_lang.php
language/hindi/form_validation_lang.php

Highlight missing translation in hindi.

Correct translation key error in arabic.

---

language/latvian/calendar_lang.php
language/latvian/date_lang.php
language/latvian/db_lang.php
language/latvian/email_lang.php
language/latvian/form_validation_lang.php
language/latvian/ftp_lang.php
language/latvian/imglib_lang.php
language/latvian/index.html
language/latvian/migration_lang.php
language/latvian/number_lang.php
language/latvian/pagination_lang.php
language/latvian/profiler_lang.php
language/latvian/unit_test_lang.php
language/latvian/upload_lang.php

Latvian language translation files for CodeIgniter 3

Latvian language translation files

---

README.rst

Added Latvian

---

README.rst
changelog.rst
core/MY_Lang.php

Added changelog & MY_Lang with fallback.

---

core/MY_Lang.php

Thanks to Flybot for catching this :)

Fix SYSDIR

---

changelog.rst

Release prep

---

changelog.rst

Sync with framework

---

README.rst
changelog.rst

Release 3.0.4

---

README.rst

Hello! I was grabbing the translation today and noticed just a little grammar error. :stuck_out_tongue:

Just fixes the word "portuguese" in the README file.

---

language/serbian/calendar_lang.php
language/serbian/date_lang.php
language/serbian/db_lang.php
language/serbian/email_lang.php
language/serbian/form_validation_lang.php
language/serbian/ftp_lang.php
language/serbian/imglib_lang.php
language/serbian/index.html
language/serbian/migration_lang.php
language/serbian/number_lang.php
language/serbian/pagination_lang.php
language/serbian/profiler_lang.php
language/serbian/unit_test_lang.php
language/serbian/upload_lang.php

I have added Serbian language translation.

Added Serbian language.

---

language/serbian/profiler_lang.php

Changed syntax error.

---

language/ukrainian/migration_lang.php

fix translate

---

language/croatian/calendar_lang.php
language/croatian/date_lang.php
language/croatian/db_lang.php
language/croatian/email_lang.php
language/croatian/form_validation_lang.php
language/croatian/ftp_lang.php
language/croatian/imglib_lang.php
language/croatian/index.html
language/croatian/migration_lang.php
language/croatian/number_lang.php
language/croatian/pagination_lang.php
language/croatian/profiler_lang.php
language/croatian/unit_test_lang.php
language/croatian/upload_lang.php

Just added the croatian translation.

Croatian language added

---

language/arabic/calendar_lang.php

it's from "اثنين" -two- with 'hamzat wasl' (همزة وصل) not 'hamzat khataa' (همزة قطع) !

update "monday" translation

---

language/bulgarian/form_validation_lang.php

Related to https://github.com/bcit-ci/CodeIgniter/issues/5590
Signed-off-by:Ivan Tcholakov <ivantcholakov@gmail.com>

'form_validation_valid_base64' message, the Bulgarian translation.

---

language/portuguese-brazilian/form_validation_lang.php

 add new line valid_base64 for brazilian portuguese

---

language/french/imglib_lang.php

J'ai corrigé quelques typo et remplacé librairie par bibliothèque.
Typos and replace 'librarie' by 'bibliothèque'.

Librairie -> bibliothèque

---

language/basque/calendar_lang.php
language/basque/date_lang.php
language/basque/db_lang.php
language/basque/email_lang.php
language/basque/form_validation_lang.php
language/basque/ftp_lang.php
language/basque/imglib_lang.php
language/basque/index.html
language/basque/migration_lang.php
language/basque/number_lang.php
language/basque/pagination_lang.php
language/basque/profiler_lang.php
language/basque/unit_test_lang.php
language/basque/upload_lang.php

Hi!
When Codeigniter translation files where managed in a wiki page, I maintained there the basque translation section. I would like to incorporate basque translation here.
Thanks,
Ander Goñi.

basque language pack added
